apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kk4kdzf77-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kk4kdzf77-java-quarkus-gitops